### ISSUE TITLE
A problem in download_imgs.py

### ISSUE THREAD

**Issue by shilida** [akshitac8/BiAM#19]
` df_image = pd.read_csv(path+data_set+'/images.csv')`
Where can I download this images.csv？
Thanks!

**Comment by akshitac8** [comment]
Hello @shilida 
You can find the missing files from these folders. Thank you so much for reporting it :)

Please download and extract class information (https://storage.googleapis.com/openimages/2017_11/classes_2017_11.tar.gz), image urls (https://storage.googleapis.com/openimages/2017_11/images_2017_11.tar.gz) and annotations (https://storage.googleapis.com/openimages/2017_11/annotations_human_2017_11.tar.gz) into the 2017_11 folder in order to download the images.

**Comment by shilida** [comment]
Thanks!!!Thank you for your reply！

**Comment by Sen-Ran** [comment]
@shilida  Have you successfully downloaded the OpenImagesV4 dataset?

**Comment by MuqaddasGull** [comment]
> @shilida Have you successfully downloaded the OpenImagesV4 dataset?

hello
Have you successfully downloaded the OpenImagesV4 dataset?
I am unable to download while donwloading and running the file names [download_imgs.py](https://github.com/akshitac8/BiAM/blob/main/datasets/OpenImages/download_imgs.py) its giving me error of not found drop image. Can you please guide me why this is happening?
